In [1]:
import pandas as pd
import numpy as np
import os
import sys
from scipy.stats import zscore
import scipy.io

import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
A = np.array([[0, 1, 1], [1, 0, 0], [1, 0,0]])
A

array([[0, 1, 1],
       [1, 0, 0],
       [1, 0, 0]])

In [35]:
D = np.diag(A.sum(axis=1))
D

array([[2, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [36]:
L = D - A
L

array([[ 2, -1, -1],
       [-1,  1,  0],
       [-1,  0,  1]])

In [37]:
Dhat = np.diag([1/np.sqrt(x) for x in np.diag(D)])
Dhat

array([[0.70710678, 0.        , 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        ]])

In [38]:
Lhat = np.linalg.multi_dot([Dhat, L, Dhat])
Lhat

array([[ 1.        , -0.70710678, -0.70710678],
       [-0.70710678,  1.        ,  0.        ],
       [-0.70710678,  0.        ,  1.        ]])

In [29]:
np.sqrt(1)

1.0

In [ ]:
# fpath = "/nfs/turbo/umms-indikar/shared/projects/myod/archive/myod_reprogramming/processed/hic/"



# mat = scipy.io.loadmat(fpath)
